# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-25 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend_requests',
            field=models.ManyToManyField(blank=True, related_name='friend_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
