# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-20 23:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_requests_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='product_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userp', to=settings.AUTH_USER_MODEL),
        ),
    ]
