# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_remove_requests_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'Recieved'), ('pending', 'Pending'), ('on its way', 'on its way'), ('delivered', 'delivered')], default='pending', max_length=120),
        ),
    ]
