# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-10-18 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'Recieved'), ('pending', 'Pending')], default='pending', max_length=120),
        ),
    ]
