# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-11-04 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_friend_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=120),
        ),
    ]
