# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-19 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='userp',
            field=models.ManyToManyField(blank=True, related_name='product_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
