# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-09-23 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_userp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destination',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
