# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-12-10 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20190923_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='product_viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
